version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: BW&&6gmKP@AQna
      POSTGRES_DB: expensestracker
    volumes:
      - data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8765:8080

  backend:
    build:
      context: api
    volumes:
      - .:/src
    ports:
      - 3100:3100
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    depends_on:
      - db

  frontend:
    build:
      context: frontend
    volumes:
      - .:/src
    ports:
      - 5173:80
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true

volumes:
  data: